[tool.poetry]
name = "djangocms_calameo"
version = "4.0.1"
description = "Django CMS Calaméo is a plugin for Django CMS that allows you to add Calaméo widgets on your site."
authors = ["Kapt dev team <dev@kapt.mobi>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://gitlab.com/kapt/open-source/djangocms-calameo"

[tool.poetry.dependencies]
python = ">=3.8"
Django = ">=1.11"
django-cms = ">=3.8"

[tool.poetry.dev-dependencies]
gitchangelog = "^3.0.4"
bumpversion = "^0.6.0"
black = "23.1.0"
flake8 = "6.0.0"
isort = "5.12.0"

[build-system]
requires = ["poetry-core>=1.5.1"]
build-backend = "poetry.core.masonry.api"
