[tool.poetry]
name = "mower-cli"
version = "0.1.1"
description = ""
authors = ["Benoit Puertolas"]
readme = "README.md"
packages = [
    { include = "mower" },
]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2.4.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[tool.poetry.scripts]
mower-cli = 'mower.controller.cli_controller:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
