[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "installPhdl"
version = "0.8.10"
license = { text="MIT" }
authors = [
    { name="MrChad", email="mrchad0815@icloud.com"},
]
description = "Install PhotoLibDownloader GUI"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "pyinstaller >= 5.13.2"
]

[project.scripts]
installPhdl = "installPhdl.installPhdl:main"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)

[tool.setuptools.package-data]
installPhdl = ["*.whl"]
