[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "rtsdkdev"
version = "0.1.4"
description = "Python package for Retool RPC"
authors = [ "huytool157 <pham@retool.com>",]
license = "MIT"
repository = "https://github.com/tryretool/rtsdk"
homepage = "https://retool.com"
readme = "README.md"
[[tool.poetry.packages]]
include = "rtsdkdev"

[tool.black]
preview = true

[tool.ruff]
src = [ "rtsdkdev",]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
asyncio = "^3.4.3"

[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
ruff = "^0.0.292"
pytest = "^7.4.2"
semver = "^3.0.2"
toml = "^0.10.2"
types-requests = "^2.31.0.8"
pytest-asyncio = "^0.21.1"
types-toml = "^0.10.8.7"
aioresponses = "^0.7.4"
requests-mock = "^1.11.0"
