[tool.poetry]
name = "redshift-data-api"
version = "0.5.0"
description = ""
authors = ["Giacomo Tagliabue <giacomo.tag@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.28.61"
pandas = "^1.2.3"

[tool.poetry.dev-dependencies]
fourmat = "^0.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target_version = ['py310']
