[tool.poetry]
name="docxparsr"
version="0.1.7"
description="Parse docx files"
authors=["Polyhedron"]
license="MIT"
readme="README.md"
packages=[{include="docxparsr", from="src"}]

[tool.poetry.dependencies]
python="^3.10"
lxml="^4.9.3"

[build-system]
requires=["poetry-core"]
build-backend="poetry.core.masonry.api"
