[tool.poetry]
name = "sihl"
version = "0.0.3-dev10"
description = "Simple Image Heads and Layers"
authors = ["jonregef <jon.regef@pm.me>"]
readme = "README.md"
license = "MIT"
# homepage = "https://github.com/sihlAI/sihl"
# repository = "https://github.com/sihlAI/sihl"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
torchmetrics = "^0.11.4"
lightning = { version = "^2.0.2", optional = true }
timm = { version = "^0.9.2", optional = true }
importlib-resources = { version = "==5.12.0", markers = "python_version < '3.9'" }
torch = "^2.1.0"
torchvision = "^0.16.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.2.0"
ruff = "^0.0.264"
pytest = "^7.3.1"
coverage = "^7.2.5"
isort = "^5.12.0"
pyupgrade = "^3.3.2"
kaggle = "^1.5.13"
torchinfo = "^1.7.2"
lightning = "^2.0.2"
tensorboard = "^2.13.0"
types-pyyaml = "^6.0.12.10"
pycocotools = "^2.0.6"

[tool.poetry.extras]
lightning = ["lightning"]
timm = ["timm"]
all = ["lightning", "timm"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["sihl", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 90

[tool.isort]
profile = "black"
force_single_line = false
lines_after_imports = 2

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
ignore_missing_imports = true
no_warn_unused_ignores = true
implicit_reexport = true

[tool.pyright]
venvPath = "."
venv = ".venv"
