[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
    "env/",
    "build_steps.txt",
    "tests/models"
]

[project]
name = "QtGraphVisuals"
version = "0.0.8"
authors = [
  { name="Jacob Botimer", email="botimerj@gmail.com" },
]
description = "A qt-widget to visualize directed graphs"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["networkx", "pyside6", "qt-material", "numpy"]

[project.urls]
"Homepage" = "https://github.com/jake987654321/QtGraphVisuals"
"Bug Tracker" = "https://github.com/jake987654321/QtGraphVisuals/issues"
