[package]
authors = ["GoRules Team <bot@gorules.io>"]
description = "Business rules engine"
name = "zen-engine"
license = "MIT"
version = "0.14.0"
edition = "2021"
repository = "https://github.com/gorules/zen.git"

[lib]
doctest = false

[dependencies]
async-recursion = "1.0.5"
anyhow = "1.0.71"
thiserror = "1.0.40"
async-trait = "0.1.68"
bincode = { version = "2.0.0-rc.3", optional = true }
petgraph = "0.6.4"
serde_json = { version = "1.0.96", features = ["arbitrary_precision"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_v8 = { version = "0.121.0" }
once_cell = { version = "1.18.0" }
futures = "0.3.28"
v8 = { version = "0.76.0" }
zen-expression = { path = "../zen-expression", version = "0.14.0" }

[features]
bincode = ["dep:bincode"]

[[bench]]
harness = false
name = "engine"
