[tool.poetry]
name = "zsdk"
version = "1.1.3.1"
description = "Unofficial Python SDK for Zscaler public API endpoints."
authors = ["Ryan Ulrick <rulrick@zscaler.com>"]
readme = "README.md"
packages = [{include = "zsdk"}]

[tool.poetry.dependencies]
python = ">=3.9"
requests = "^2.31.0"
urllib3 = "^2.0.4"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
pytest = "^7.4.0"
black = "^23.7.0"
tomli = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = ["tool.poetry"]

[project.urls]
"Homepage" = "https://github.com/SYNically-ACKward/zsdk"