[tool.poetry]
name = "ch.sachi.powermonitor"
version = "0.1.6"
description = ""
authors = ["Patrick Zbinden <patrick+dev@zbinden-online.ch>"]
readme = "README.md"
packages = [{include = "ch", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
victron-ble = "^0.6.0"
requests = "^2.31.0"

[tool.poetry.scripts]
savePowerMonitor = 'ch.sachi.powermonitor:main'

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
coverage = "^7.3.1"
pytest-mock = "^3.11.1"
pytest-mockito = "^0.0.4"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
