


#
#	HOW TO PUBLISH:
#
#		(rm -rf dist && python3 -m build --sdist && twine upload dist/*)
#		(git add --all && git commit -m "com" && git push --set-upstream git@gitlab.com:reptilian_climates/CYTE.git CLIMATE)
#

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CYTE"
version = "0.0.2"
description = "MEASUREMENTS (System International, US Customary, etc.)"
readme = "CYTE.txt"

[tool.setuptools.packages.find]
where = [ "LOVELY/STRUCTURES" ]

#
#	https://setuptools.pypa.io/en/latest/userguide/datafiles.html
#
[tool.setuptools.package-data]
"*" = [ "*.HTML" ]