[package]
authors = ["GoRules Team <bot@gorules.io>"]
description = "Zen Expression Language"
name = "zen-expression"
license = "MIT"
version = "0.14.0"
edition = "2021"
repository = "https://github.com/gorules/zen.git"

[dependencies]
ahash = "0.8.3"
bumpalo = "3.13.0"
chrono = "0.4.26"
hashbrown = { version = "0.13.2", features = ["bumpalo"] }
humantime = "2.1.0"
fastrand = "2.0.0"
once_cell = "1.17.2"
phf = { version = "0.11.1", features = ["macros"] }
regex = { version = "1.9.1", optional = true }
regex-lite = { version = "0.1.0", optional = true }
serde = "1.0.188"
serde_json = { version = "1.0.96", features = ["arbitrary_precision"] }
thiserror = "1.0.40"
rust_decimal = { version = "1.29.1", features = ["maths-nopanic"] }
rust_decimal_macros = "1.29.1"

[features]
default = ["regex-deprecated"]
regex-deprecated = ["dep:regex"]
regex-lite = ["dep:regex-lite"]

[[bench]]
harness = false
name = "unary"

[[bench]]
harness = false
name = "standard"

[[bench]]
harness = false
name = "lexer"

[[bench]]
harness = false
name = "isolate"
