[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "saipy"
version = "0.0.4"
authors = [
  { name="Megha, Wei, and Nishtha", email="sai_group@gmail.com" },
]
description = "Deep learnig-based seismological application"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
  ]

  [project.urls]
  "Homepage" = "https://github.com/srivastavaresearchgroup/SAIPy"
  "Bug Tracker" = "https://github.com/srivastavaresearchgroup/SAIPy/issues"