[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "threadingwebdriver"
version = "0.0.2"
authors = [
  { name="Chor", email="chorong8883@gmail.com" },
]
description = "Selenium webdriver using thread pool. (Chrome only now.)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "selenium>=4.14",
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
"Homepage" = "https://github.com/chorong8883/threadingwebdriver"