[project]
name = "dtaianomaly"
version = "0.0.1"
description = "A simple-to-use Python package for the development and analysis of time series anomaly detection techniques."
readme = "README.md"
authors = [
    {name = "Louis Carpentier", email = "louis.carpentier@kuleuven.be"}
]
keywords = [
    "machine-learning",
    "time-series",
    "anomaly-detection"
]
requires-python = ">=3.9,<3.10"
dependencies = [
    "numpy==1.23.0",
    "pyod==1.1.0",
    "matplotlib==3.8.0",
    "pandas==2.1.1",
    "scipy==1.11.2",
    "scikit-learn~=1.2.2"
]
[project.urls]
repository = "https://gitlab.kuleuven.be/u0143709/dtaianomaly"

[project.license]
file = "LICENSE"

[build-system]
requires = ["setuptools", "wheel", "toml", "build"]
build-backend = "setuptools.build_meta"