[tool.poetry]
name = "download-latest"
version = "0.1.0"
description = "Download a file only if the remote file has changed."
license = "GPL-3.0-or-later"
authors = ["JƒÅgaro <jagaro@dayam.org>"]
readme = "README.md"
homepage = "https://gitlab.com/jagaro/download-latest"
repository = "https://gitlab.com/jagaro/download-latest"
keywords = ["curl", "download", "wget"]
classifiers = [
    "Programming Language :: Python :: 3.12"
]
include = ["INSTALL.md"]

[tool.poetry.dependencies]
python = "^3.7"
importlib-metadata = { version = ">=3.0.0", python = "<3.8" }

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
mypy = "*"
nox = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-watcher = "*"
ruff = "*"
# We must pin this particular version of typing-extensions for dmypy to work.
# See https://github.com/python/mypy/issues/15854.
typing-extensions = "<4.7.0"

[tool.poetry.scripts]
download-latest = "download_latest.console:main"
dl = "download_latest.console:main"

[tool.pytest.ini_options]
addopts = "--color=yes --quiet"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
