[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "best_csv"
version = "1.1"
authors = [
  { name="Alexios Nersessian", email="nersessian@gmail.com" },
]
description = "Smarter Faster way from CSV to dict."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/alekos3/best_csv.git"
