# SPDX-FileCopyrightText: 2023 Ngô Ngọc Đức Huy <huyngo@disroot.org>
#
# SPDX-License-Identifier: GPL-3.0-only

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rasc"
authors = [{name = "Ngô Ngọc Đức Huy", email = "huyngo@disroot.org"}]
license = {file = "LICENSES/GPL-3.0-only.txt"}
classifiers = ["License :: OSI Approved :: GNU General Public License v3 (GPLv3)"]
dynamic = ["version", "description"]
readme = "README.md"

[project.urls]
Home = "https://git.sr.ht/~huyngo/rasc/"

[project.scripts]
rasc-demo = "rasc:lax"
rasc-strict = "rasc:strict"
