[tool.poetry]
name = "tickerdax"
version = "0.0.82"
description = "A python client for tickerdax.com with a built-in caching system."
authors = ["tickerdax.com <info@tickerdax.com>"]
readme = "README.md"
repository = "https://github.com/tickerdax/tickerdax-client"
#documentation =
license = "MIT"
packages = [
    {include = "tickerdax"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.scripts]
tickerdax = "tickerdax.cli:app"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tickerdax/tickerdax-client/issues"

[tool.poetry.dependencies]
python = ">=3.7,<4.0.0"
typer = {extras = ["all"], version = "^0.7.0"}
tomlkit = "^0.11.6"
redis = "^4.1.4"
docker = "^6.0.1"
fastapi = "0.*"
uvicorn = "0.*"
pyyaml = "^6.0"
schema = "^0.7.5"
websockets = [
    {version = "^9.1.0", python = ">=3.7,<3.10"},
    {version = "^10.4", python = "==3.10"},
    {version = "^11.0.3", python = ">=3.11"}
]
art = "^5.8"
python-dotenv = "^0.19.2"
jinja2 = "^3.1.2"
python-dateutil = "^2.8.2"
sentry-sdk = ">=1.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
jinja2 = "^3.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
