[project]
name = "nonebot-plugin-batitle"
version = "0.1.1"
description = "BlueArchive Title Generator"
authors = [
    { name = "MerCuJerry", email = "mercujerry@gmail.com" },
]
dependencies = [
    "nonebot2 >= 2.1.0",
    "nonebot-adapter-onebot>=2.3.1",
    "pillow <10.0.0, >=9.2.0",
]
requires-python = ">=3.11"
readme = "README.md"

[project.license]
file = "LICENSE"

[project.urls]
homepage = "https://github.com/MerCuJerry/nonebot-plugin-batitle"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = [
    "nonebot_plugin_batitle",
]
