[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "algoind"
version = "0.0.1"
authors = [
  { name="Matteo Incremona", email="matteoincremona82@gmail.com" },
]
description = "A collection of technical indicators for backtesting and for implementing trading strategies in Python3."
readme = "README.md"
license = {file = "LICENSE.txt"}
keywords = ["finance", "indicator", "backtesting", "trading", "pandas","quantitative"]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/matteoincremona/techind"
"Bug Tracker" = "https://github.com/matteoincremona/techind/issues"
