[tool.poetry]
name = "agl-frame2vid"
version = "0.1.2"
description = "Frame Extraction"
authors = ["Thomas J. Lux"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.11,<3.13"
opencv-python = "^4.8.1.78"
python-ffmpeg = "^2.0.4"
numpy = "^1.26.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
