[tool.poetry]
name = "flake8-import-relative-two"
version = "0.1.0"
description = "Flake8 plugin that checks for relative imports up to a maximum of level two"
repository = "https://github.com/bartoszcholewa/flake8-import-relative-two"
authors = ["Bartosz Cholewa <bbcholewa@gmail.com>"]
license = "MIT License"
readme = "README.md"
packages = [{include = "flake8_import_relative_two"}]
keywords = [
    "flake8-plugin",
    "linting",
    "absolute-imports",
    "relative-imports",
]
classifiers = [
    "License :: OSI Approved",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Framework :: Flake8",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Quality Assurance",
    "Development Status :: 5 - Production/Stable",
]

[tool.poetry.dependencies]
python = "^3.10"
wheel = "^0.41.2"
setuptools = ">=61.2"
flake8 = "^6.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
black = "^23.9.1"
pytest-cov = "^4.1.0"
tox = "^4.11.3"
codecov = "^2.1.13"

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["docs", "*.egg-info", ".git", ".tox", "var/large_ml_model/"]
addopts = "-s -x -p no:cacheprovider --durations=10"

[tool.poetry.plugins]
[tool.poetry.plugins."flake8.extension"]
IRT1 = "flake8_import_relative_two:Plugin"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
